spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        jdbc.batch_size: ${batchSize}
        order_inserts: true
        order_updates: true
        generate_statistics: true
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: MYSQL


batchSize: 1000


logging.level.org.hibernate.stat: debug